version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./backend/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build: ./backend
    container_name: backend-container
    volumes:
      - .:/backend
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db:db
    environment:
      - DB_SERVER=db
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  frontend:
    container_name: frontend-container
    ports:
      - "3000:3000"
    volumes:
      - .:/frontend
    build: ./frontend


